import React from 'react'
import './globals.css'

export const metadata = {
  title: 'Horoprism Project',
  description: 'Generated by create ',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className='h-screen background'>        
        {children}
      </body>
    </html>
  )
}
